# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  makeupbysamy.com:
    site_hosts:
      - canonical: makeupbysamy.test
        redirects:
          - www.makeupbysamy.test
    local_path: ../makeupbysamy.com # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@makeupbysamy.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false

  staging.makeupbysamy.com:
    site_hosts:
      - canonical: staging.makeupbysamy.test
        redirects:
          - www.makeupbysamy.test
    local_path: ../staging.makeupbysamy.com # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@staging.makeupbysamy.com
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false

